### ISSUE TITLE
How can I convert a Ruby array of Ve::Word objects into JSON?

### ISSUE THREAD

**Issue by fasiha** [Kimtaro/ve#24]
Ruby nub question: how can I convert, e.g., `words` in `words = Ve.in(:en).words('I like melons.')` to JSON?

(I need to parse thousands of sentences and I'm hoping using the native Ruby front-end will be faster than going through JavaScript and hitting Sinatra thousands of times. I'm hoping I can just `cat file | ruby ve.ruby > results.txt` and have each line of `results.txt` be a complete JSON object.)

**Comment by fasiha** [comment]
The answer was in `sinatra/server.rb`: `JSON.generate(words.collect { |w| w.as_json(true) })`.

**Comment by Kimtaro** [comment]
:+1:
