### ISSUE TITLE
Hi Kimtaro, I made a dotnet version of mecab_ipadic.rb

### ISSUE THREAD

**Issue by luojunyuan** [Kimtaro/ve#48]
I use MIT license for the [library](https://github.com/luojunyuan/Ve.DotNet). Should I merge the code into this repository?

**Comment by Kimtaro** [comment]
@luojunyuan that’s awesome!

I’m starting to think it’s best to keep each language port in separate repos. So I suggest keeping it like you have it now, but if you wouldn’t mind sending a PR to this repo that adds a link in the readme to your repo I’d be more than happy to merge that.
